# Generated by Django 5.2 on 2025-04-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authorbio',
            table='author_bio',
        ),
    ]
