# Generated by Django 5.1.7 on 2025-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author_alter_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Science', 'Science'), ('Cooking', 'Cooking'), ('Business', 'Business'), ('Psychology', 'Psychology'), ('History', 'History')], max_length=30),
        ),
    ]
