# Generated by Django 5.2 on 2025-04-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_discounted_price_book_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='isbn_index'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn', 'language'], name='isbn_lang_index'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0)), name='negative_rating_constraint'),
        ),
    ]
